# Generated by Django 4.1.3 on 2023-01-13 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='views',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
